# DSE I1020 — Data Structures & NumPy (60‑min practicum)
*Live, guided coding — City College of New York, DSE I1020*

**Session length:** 60 minutes  
**Run in:** Google Colab (or local Jupyter)  
**Generated:** 2025-09-08 20:19

**References**
- *Scipy Lecture Notes*
- *Python Data Science Handbook* (Jake VanderPlas)
- *Elements of Data Science* (Allen Downey)

## 0–5 min — Orientation
**Instruction:** Create a simple Python list and demonstrate basic indexing.
- Make `a = [1, 2, 3]`
- Print the first and last elements
- Explain in a comment what 0-based indexing means.

In [27]:
a=[1,2,3]
print(a[0])
print(a[len(a)-1])

1
3


## 5–15 min — Arrays via Python Lists
**Instruction:** Using `a = [5.3, 2.1, 6.9, 4.2, 7.7]`, perform:
1) indexed access, 2) update an element, 3) append items, 4) delete from middle,
5) insert at arbitrary position. Print after each step.

In [28]:

b=[1,2,3,4,5]
c= b[:3] + [99] +b [3:]
c


[1, 2, 3, 99, 4, 5]

**Instruction:** Show three insertion strategies to place `99` before `4` in `b = [1,2,3,4,5]`:
(a) `insert`, (b) slice assignment, (c) concatenation.

In [29]:
b.insert(3,99)
b

[1, 2, 3, 99, 4, 5]

In [30]:
b=[1,2,3,4,5]
c=[0,0,0,0,0,0]
c[0:3]=b[:3]
c[3] =99
c[4:6] =[4,5]
c


[1, 2, 3, 99, 4, 5]

## 15–25 min — Lists as Stack & Queue + Useful Methods
**Instruction (Stack):** Use a list as a stack. Push 3 strings, peek the top, pop until empty.
**Instruction (Methods):** On `data = [3,1,4,1,5,9,2,6,5]` show `count`, `index`, `remove`, `reverse`, `sort`.
**Instruction (Queue):** Implement `enqueue(q,x)` inserting at front and `dequeue(q)` removing from back; demo with `'A','B','C'`.

In [31]:
data =[3,1,4,1,5,9,2,6,5]

def enqueue(lst, element):
  new_lst = []
  new_lst= [element] + lst
  return new_lst

enqueue(data,99)

[99, 3, 1, 4, 1, 5, 9, 2, 6, 5]

## 25–35 min — Linked Lists (Nodes, HEAD/END, Traversal, Aliasing)
**Instruction:** Implement a minimal singly linked list with `Node(val, next)`.
- Create `head=None`; prepend 3 nodes; then append one node at tail.
- Traverse and collect values.
- Show aliasing: create `x = [1, [2, 3]]`; set `y = x`; mutate inner list and inspect `id(...)` values.

## 35–42 min — Key–Value Stores / Hash Tables (`dict`)
**Instruction:** Create a small phone-book dict; add, update, and delete entries; show membership and safe access with `get()`.

## 42–50 min — Tabular Data as Dict‑of‑Lists
**Instruction:** Build a dict-of-lists table, print columns and rows, and compute a derived column.
- Create `students = {'name': [...], 'grade': [...], 'credits': [...]}`
- Row 0 as a record; column access; add `quality_points = grade * credits`.

## 50–57 min — NumPy Arrays & Vectorization
**Instruction:** Create arrays and inspect attributes; slice and do element‑wise operations.
- `np.array`, `np.zeros`, `np.arange`
- Show `.shape`, `.dtype`, `.ndim`
- Demonstrate slicing and vectorized arithmetic

In [32]:
import numpy as np
np_b=np.array(b)
np_b


array([1, 2, 3, 4, 5])

In [33]:
np_b.shape

(5,)

In [34]:
np_b.dtype

dtype('int64')

## 57–60 min — NumPy Broadcasting
**Instruction:** Show scalar→array and vector→matrix broadcasting.
- Add 5 to a vector
- Add a column vector to a 2D matrix and verify result shapes

In [35]:
np_b+5

array([ 6,  7,  8,  9, 10])

In [36]:
np_b.transpose()

array([1, 2, 3, 4, 5])

In [37]:
np_c = np.array([[1,2,3,4,5]]).transpose()
np_c.shape

(5, 1)

In [41]:
np_d =np_b+np_c
np_d



array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])